// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWez2Wxvadko3pB5B0TT9m-oI-k3JZW6k',
    appId: '1:686612449965:web:56c8d30b2c23fdf822d424',
    messagingSenderId: '686612449965',
    projectId: 'egons-flutter-sandbox',
    authDomain: 'egons-flutter-sandbox.firebaseapp.com',
    storageBucket: 'egons-flutter-sandbox.appspot.com',
    measurementId: 'G-FQXGY3XY6F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm3kY67Cx65NpMhs6B43lUHn40Nf4QaEY',
    appId: '1:686612449965:android:6acb05d1e372da7322d424',
    messagingSenderId: '686612449965',
    projectId: 'egons-flutter-sandbox',
    storageBucket: 'egons-flutter-sandbox.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuUPphi_R7B2hvrvaLkoObOW4dw0UQbqk',
    appId: '1:686612449965:ios:03793c6131e0bc7822d424',
    messagingSenderId: '686612449965',
    projectId: 'egons-flutter-sandbox',
    storageBucket: 'egons-flutter-sandbox.appspot.com',
    iosClientId: '686612449965-v27tgc6ei8gda84uj7a00nfmu1ms7tmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.sandbox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuUPphi_R7B2hvrvaLkoObOW4dw0UQbqk',
    appId: '1:686612449965:ios:03793c6131e0bc7822d424',
    messagingSenderId: '686612449965',
    projectId: 'egons-flutter-sandbox',
    storageBucket: 'egons-flutter-sandbox.appspot.com',
    iosClientId: '686612449965-v27tgc6ei8gda84uj7a00nfmu1ms7tmh.apps.googleusercontent.com',
    iosBundleId: 'com.example.sandbox',
  );
}
